Temporary verbosity increase for #227

diff --git a/plexupdate-core b/plexupdate-core
--- a/plexupdate-core
+++ b/plexupdate-core
@@ -178,26 +178,35 @@ getLocalSHA() {
 
 # RNNG
 running() {
+	printf 'Entered running'
 	# If a server is unclaimed, it probably doesn't have TLS enabled either
 	local DATA
 	# get Plex sessions
 	DATA="$(wget -q -O - http://$1:$2/status/sessions)"
 	local RET=$?
+	printf 'First wget returned %b, with data:\n%b\n\n' "$RET" "$DATA"
 	# and live TV/DVR sessions
 	DATA+="$(wget -q -O - http://$1:$2/livetv/sessions)"
+	printf 'Second wget returned %b, data is now:\n%b\n\n' "$?" "$DATA"
 
 	if [ ${RET} -eq 6 ]; then
+		printf 'Entering https block'
 		# Server may be claimed, in which case we should use TLS and pass a token
 		getPlexToken
+		[ -n "$TOKEN" ] && printf 'TOKEN is non-zero, continuing'
 		DATA="$(wget --no-check-certificate -q -O - https://$1:$2/status/sessions?X-Plex-Token=$TOKEN)"
 		RET=$?
+		printf 'First https wget returned %b, with data:\n%b\n\n' "$RET" "$DATA"
 		DATA+="$(wget --no-check-certificate -q -O - https://$1:$2/livetv/sessions?X-Plex-Token=$TOKEN)"
+		printf 'Second https wget returned %b, data is now:\n%b\n\n' "$?" "$DATA"
 	fi
 
 	if [ ${RET} -eq 0 ]; then
 		# Get a total count of active media (MediaContainer size), then deduct one for every paused stream.
 		# If all streams are paused, we consider the server to not be active.
-		local mediacount="$(awk -F'"' '/<MediaContainer size="[0-9]+">/ {count+=$2}; /<Player[^>]* state="paused"/ {count--}; END {print count}' <<< ${DATA})"
+		local mediacount
+		mediacount="$(awk -F'"' '/<MediaContainer size="[0-9]+">/ {count+=$2}; /<Player[^>]* state="paused"/ {count--}; END {print count}' <<< ${DATA})" || printf 'mediacount awk call failed'
+		printf 'mediacount is now "%b"' "$mediacount"
 		[ $mediacount -gt 0 ] && return 0
 	fi
 
